# Generated by Django 3.2.20 on 2026-03-18 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MO', 'Москва'), ('SP', 'Санкт-Петербург'), ('NN', 'Нижний Новгород'), ('PE', 'Пермь'), ('VA', 'Всероссийская академия внешней торговли')], max_length=2), default=list, size=None),
        ),
    ]
