# Generated by Django 3.1.7 on 2021-04-25 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MO', 'Москва'), ('SP', 'Санкт-Петербург'), ('NN', 'Нижний Новгород'), ('PE', 'Пермь')], max_length=2), default=list, size=None),
        ),
    ]
