# Generated by Django 3.1.5 on 2021-03-10 18:16

import common.models.subjects
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('patronymic', models.CharField(blank=True, max_length=32)),
                ('rel_status', models.CharField(choices=[('father', 'отец'), ('mother', 'мать'), ('sister', 'сестра'), ('brother', 'брат')], max_length=32)),
                ('birthdate', models.DateField()),
                ('citizenship', models.CharField(max_length=32)),
                ('pers_mobile', models.CharField(blank=True, max_length=15)),
                ('permanent_address', models.CharField(max_length=64)),
                ('place_birth', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('annotation', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=common.models.subjects.super_user_id, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
