# Generated by Django 3.1.5 on 2021-02-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('patronymic', models.CharField(blank=True, max_length=32)),
                ('rel_status', models.CharField(choices=[('father', 'отец'), ('mother', 'мать'), ('sister', 'сестра'), ('brother', 'брат')], max_length=32)),
                ('birthdate', models.DateField()),
                ('citizenship', models.CharField(max_length=32)),
                ('pers_mobile', models.CharField(blank=True, max_length=15)),
                ('permanent_address', models.CharField(max_length=64)),
                ('place_birth', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'abstract': False,
            },
        ),
    ]
