version: "3"

# Typical order of declarations for every service:
# - image
# - container_name
# - build
# - env_file
# - ports
# - command
# - restart
# - volumes
# - depends_on

services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - /opt/dal/postgres-data:/var/lib/postgresql/data

  # quizzes-db:
  #   image: postgres:13-alpine
  #   env_file:
  #     - .env
  #     - quizzes/.env
  #   restart: always
  #   volumes:
  #     - /opt/dal/quizzes-data:/var/lib/postgresql/data

  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --config=/ofelia/config.ini
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia:/ofelia:ro

  watchdoc:
    build:
      context: .
      dockerfile: watchdoc/Dockerfile
    env_file:
      - .env
      - watchdoc/.env
    restart: always
    volumes:
      - watchdoc-generated:/watchdoc/generated
      - watchdoc-secrets:/watchdoc/secrets

  back-end:
    container_name: back-end
    build:
      context: .
      dockerfile: back-end/docker/image/prod.dockerfile
    env_file:
      - .env
      - back-end/.env
    command: >
      sh -c "/tools/wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT -t 0 &&
             python manage.py migrate &&
             python manage.py register_permissions &&
             rm -rf static &&
             python manage.py collectstatic --clear &&
             gunicorn conf.wsgi:application --config src/gunicorn.conf.py"
    restart: always
    volumes:
      - /opt/dal/back-end-backups:/back-end/backups
      - /opt/dal/back-end-media:/back-end/media
    depends_on:
      - postgres

  front-end:
    build:
      context: .
      dockerfile: front-end/Dockerfile
      args:
        - VUE_APP_BACK_END_HOST=$BACK_END_HOST
        - VUE_APP_BACK_END_PORT=$BACK_END_PORT
    env_file:
      - .env
    volumes:
      - frontend-dist:/dist
    command: >
      sh -c "cp -r /front-end/dist/* /dist/ && tail -f /dev/null"
    restart: "no"

  tgbot:
    container_name: tgbot
    build:
      context: .
      dockerfile: tgbot/Dockerfile
    env_file:
      - .env
      - tgbot/.env
    restart: always

  # quizzes:
  #   build:
  #     context: .
  #     dockerfile: quizzes/Dockerfile
  #   env_file:
  #     - quizzes/.env
  #   depends_on:
  #     - quizzes-db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot:/etc/letsencrypt:ro
      - webroot:/var/www/certbot:ro
      - frontend-dist:/usr/share/nginx/html:ro
    depends_on:
      - back-end
      - front-end

  certbot:
    image: certbot/certbot
    volumes:
      - certbot:/etc/letsencrypt
      - webroot:/var/www/certbot

  renew:
    image: certbot/certbot
    volumes:
      - certbot:/etc/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: >
      sh -c "
        while sleep 12h; do
          certbot renew --webroot -w /var/www/certbot --deploy-hook 'nginx -s reload || echo reload_failed' ;
        done
      "

volumes:
  watchdoc-generated:
  watchdoc-secrets:
  certbot:
  webroot:
  frontend-dist:
