from collections import namedtuple

Data = namedtuple(
    "Data",
    [
        "email",
        "password",
        "is_staff",
        "is_superuser",
        "campuses",
    ],
)


def get_users():
    return [
        Data(
            email="bphodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="afhodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ppkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="patishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dfdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aftishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fpdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ddtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="afdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fptishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="abtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bptishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pakretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aatishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pbtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fakretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="abhodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bbzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pptishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dphodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fftishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dbdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="abzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="adhodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ffdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bbtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aphodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bpkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fazakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dazakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bpdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pfdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fbdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dfkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dftishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fdtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fddemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ffhodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aakretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
    ]
