
from conf.settings import TEST_CORPORATE_EMAIL_DOMAIN

from collections import namedtuple

from django.contrib.auth import get_user_model

from conf.settings import TGBOT_EMAIL, TGBOT_PASSWORD

from common.models.universities import Campus

Data = namedtuple(
    "Data",
    [
        "email",
        "password",
        "is_staff",
        "is_superuser",
        "campuses",
    ],
)

def get_users():
    return [
        
Data(email='datishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fosmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pbhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pdsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='abdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aptishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dotishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='botishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fademchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pfdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='adsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dpsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aasmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aokretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aphodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dpzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='adtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='abhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='batishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fatishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bpzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dbsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pahodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aazakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pfkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bakretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pademchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fasmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bfdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fbzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dohodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dptishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='apdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pasmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aakretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dpdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fakretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ppsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bbzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pphodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='adkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='adhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dfhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ddhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pdkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fodemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ffkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='apkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bbtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='abkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bahodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dbhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aademchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fpzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aohodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ffdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ffhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pazakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bodemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dokretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pakretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pfhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bdkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='afkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fbkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dodemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dbzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fdsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fozakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dfzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='afsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bozakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dbtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pddemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ppkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ppzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dasmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fohodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fpdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dpkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ddzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ddtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fdhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dfsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='abzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='afhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='absmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fptishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pbtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bddemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bdsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aatishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aftishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ffzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pdtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fotishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dademchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fpkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fokretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='abtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ddsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fbsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aozakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aosmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dbkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bfhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pftishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bosmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bdtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dazakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pbkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aahodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ppdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bademchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dphodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fahodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dbdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bptishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='addemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pptishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='adzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fftishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aotishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bokretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bftishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bphodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fpsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='aodemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fazakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pdzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fphodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='afdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dfkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fbdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ffsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fdtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='apsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bdzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='afzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pfsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='apzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bazakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dahodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dakretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dddemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bbhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='posmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pokretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bfsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fbhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bfkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dozakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pbzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='potishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bpkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dosmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='podemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bdhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='patishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fdzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pozakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='ddkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pbsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dftishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pbdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='basmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='dfdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bpsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pfzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bbdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bbsmirnov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bpdemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bbkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fddemchin@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bfzakudrjaev@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pohodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='pdhodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fbtishanov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='fdkretkov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
Data(email='bohodilov@mail.com', password='qwerty', is_staff=False, is_superuser=False, campuses=[Campus.MOSCOW.value]), 
]
