from collections import namedtuple

Data = namedtuple(
    "Data",
    [
        "email",
        "password",
        "is_staff",
        "is_superuser",
        "campuses",
    ],
)


def get_users():
    return [
        Data(
            email="bakretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="adtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fphodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="apzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bbtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fbdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pptishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fdzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fpkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="adkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fatishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dazakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fdkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bddemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pphodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bademchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aftishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pbtishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fdhodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ddzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ppkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="apkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bpdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="pddemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bbdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bbkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aatishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fazakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aazakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bdzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="dbkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bahodilov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="apdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="bfzakudrjaev@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="aakretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="batishanov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="ffdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="fbkretkov@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
        Data(
            email="abdemchin@mail.com",
            password="qwerty",
            is_staff=False,
            is_superuser=False,
            campuses=[("MO", "Москва")],
        ),
    ]
