export { default as DateInput} from './Date.vue'
export { default as FileInput} from './File.vue'
export { default as InputsBaseInput} from './InputsBase.vue'
export { default as NumberInput} from './Number.vue'
export { default as SelectInput} from './Select.vue'
export { default as TagsInput} from './Tags.vue'
export { default as TextInput} from './Text.vue'
