# Generated by Django 3.2.10 on 2022-11-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='visible_to_students',
            field=models.BooleanField(default=True),
        ),
    ]
