# Generated by Django 3.2.10 on 2023-02-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_add_visible_to_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dms.file'),
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dms.file'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dms.file'),
        ),
    ]
