# Generated by Django 3.2.20 on 2025-10-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_make_book_files_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='additional_schema',
            field=models.JSONField(blank=True, help_text='JSON Schema for additional fields of the category', null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='additional_fields',
            field=models.JSONField(blank=True, help_text="Additional fields specific to the category, matching the category's additional_schema", null=True),
        ),
    ]
