# Generated by Django 3.2.20 on 2026-03-07 12:09

from django.db import migrations, models
import dms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_add_paper_additional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='additional_schema',
            field=models.JSONField(blank=True, help_text='JSON Schema for additional fields of the category', null=True, validators=[dms.validators.validate_json_schema]),
        ),
    ]
