# Generated by Django 3.1.1 on 2020-09-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceStatus',
            fields=[
                ('absenceStatus', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Absence Status',
                'verbose_name_plural': 'Absence Statuses',
                'db_table': 'absenceStatus',
            },
        ),
        migrations.RemoveField(
            model_name='absence',
            name='status',
        ),
        migrations.AddField(
            model_name='absence',
            name='absenceStatus',
            field=models.ForeignKey(db_column='absenceStatus', default='Закрыт', on_delete=django.db.models.deletion.DO_NOTHING, to='lms.absencestatus'),
            preserve_default=False,
        ),
    ]
