# Generated by Django 3.1.7 on 2021-03-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_code', models.CharField(max_length=6)),
                ('passport_ufms_name', models.CharField(max_length=255)),
                ('passport_ufms_code', models.CharField(max_length=7)),
                ('passport_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=32)),
                ('group_title', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='brothers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='commissariat_city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='commissariat_district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hse_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hse_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_ufms_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_ufms_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sisters',
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brothers', models.ManyToManyField(blank=True, related_name='brothers', to='common.Relative')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='father', to='common.relative')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother', to='common.relative')),
                ('sisters', models.ManyToManyField(blank=True, related_name='sisters', to='common.Relative')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.passport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='recruitment_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.recruitmentoffice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='university_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.universityinfo'),
            preserve_default=False,
        ),
    ]
