# Generated by Django 3.1.5 on 2021-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_restrinction_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Abcense Time',
                'verbose_name_plural': 'Abcense Time',
            },
        ),
    ]
