# Generated by Django 3.1.1 on 2020-09-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20200911_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='post',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherPost',
            field=models.ForeignKey(db_column='teacherPost', default='Полковник', on_delete=django.db.models.deletion.DO_NOTHING, to='lms.teacherpost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absence',
            name='studentid',
            field=models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
        ),
    ]
