# Generated by Django 3.1.1 on 2020-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20200911_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='milgroup',
            name='weekday',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
