# Generated by Django 3.1.5 on 2021-02-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_absencetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absencetime',
            options={'verbose_name': 'Absence Time', 'verbose_name_plural': 'Abcense Time'},
        ),
        migrations.RenameField(
            model_name='absencetime',
            old_name='absence_restrinction_time',
            new_name='absence_restriction_time',
        ),
    ]
