# Generated by Django 3.1.1 on 2020-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20200922_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='milgroup',
            name='weekday',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
