# Generated by Django 3.1.1 on 2020-10-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_milgroup_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencestatus',
            old_name='absenceStatus',
            new_name='absence_status',
        ),
        migrations.RenameField(
            model_name='absencetype',
            old_name='absenceType',
            new_name='absence_type',
        ),
        migrations.RenameField(
            model_name='activitytype',
            old_name='activityType',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='controlform',
            old_name='controlForm',
            new_name='control_form',
        ),
        migrations.RenameField(
            model_name='encouragementtype',
            old_name='encouragementType',
            new_name='encouragement_type',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lessonnum',
            new_name='lesson_num',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='type',
            new_name='lesson_type',
        ),
        migrations.RenameField(
            model_name='lessontype',
            old_name='lessonType',
            new_name='lesson_type',
        ),
        migrations.RenameField(
            model_name='punishment',
            old_name='removedate',
            new_name='remove_date',
        ),
        migrations.RenameField(
            model_name='punishmenttype',
            old_name='punishmentType',
            new_name='punishment_type',
        ),
        migrations.RenameField(
            model_name='studentpost',
            old_name='studentPost',
            new_name='student_post',
        ),
        migrations.RenameField(
            model_name='teacherpost',
            old_name='teacherPost',
            new_name='teacher_post',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='encouragement',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='encouragement',
            name='teacherid',
        ),
        migrations.RemoveField(
            model_name='encouragement',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacherid',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='controlform',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='lessonid',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='punishment',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='punishment',
            name='teacherid',
        ),
        migrations.RemoveField(
            model_name='punishment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacherPost',
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_status',
            field=models.ForeignKey(db_column='absence_status', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.absencestatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(db_column='absence_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.absencetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(db_column='student', default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(db_column='activity_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.activitytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='student',
            field=models.ForeignKey(db_column='student', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encouragement',
            name='encouragement_type',
            field=models.ForeignKey(db_column='encouragement_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.encouragementtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encouragement',
            name='student',
            field=models.ForeignKey(db_column='student', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encouragement',
            name='teacher',
            field=models.ForeignKey(db_column='teacher', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(db_column='teacher', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonmilgroup',
            name='lesson',
            field=models.OneToOneField(db_column='lesson', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='control_form',
            field=models.ForeignKey(db_column='control_form', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.controlform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(blank=True, db_column='lesson', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.lesson'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(db_column='student', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punishment',
            name='punishment_type',
            field=models.ForeignKey(db_column='punishment_type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.punishmenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punishment',
            name='student',
            field=models.ForeignKey(db_column='student', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punishment',
            name='teacher',
            field=models.ForeignKey(db_column='teacher', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentskill',
            name='student',
            field=models.OneToOneField(db_column='student', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentstudentpost',
            name='student',
            field=models.OneToOneField(db_column='student', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentstudentpost',
            name='student_post',
            field=models.ForeignKey(db_column='student_post', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.studentpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_post',
            field=models.ForeignKey(db_column='teacher_post', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.teacherpost'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('date', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonmilgroup',
            unique_together={('lesson', 'milgroup')},
        ),
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='studentstudentpost',
            unique_together={('student', 'student_post')},
        ),
        migrations.AlterModelTable(
            name='absencestatus',
            table='absence_status',
        ),
        migrations.AlterModelTable(
            name='absencetype',
            table='absence_type',
        ),
        migrations.AlterModelTable(
            name='activitytype',
            table='activity_type',
        ),
        migrations.AlterModelTable(
            name='controlform',
            table='control_form',
        ),
        migrations.AlterModelTable(
            name='encouragementtype',
            table='encouragement_type',
        ),
        migrations.AlterModelTable(
            name='lessontype',
            table='lesson_type',
        ),
        migrations.AlterModelTable(
            name='punishmenttype',
            table='punishment_type',
        ),
        migrations.AlterModelTable(
            name='studentpost',
            table='student_post',
        ),
        migrations.AlterModelTable(
            name='teacherpost',
            table='teacher_post',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='absenceStatus',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='absenceType',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='lessonmilgroup',
            name='lessonid',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='studentstudentpost',
            name='studentPost',
        ),
        migrations.RemoveField(
            model_name='studentstudentpost',
            name='studentid',
        ),
    ]
