# Generated by Django 3.1.1 on 2020-09-03 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mil_lms_backend', '0001_initial_lms_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('absenceType', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Absence Type',
                'verbose_name_plural': 'Absence Types',
                'db_table': 'absenceType',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('activityType', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'db_table': 'activityType',
            },
        ),
        migrations.CreateModel(
            name='ControlForm',
            fields=[
                ('controlForm', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Form of Control',
                'verbose_name_plural': 'Forms of Control',
                'db_table': 'controlForm',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='EncouragementType',
            fields=[
                ('encouragementType', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Encouragement Type',
                'verbose_name_plural': 'Encouragement Types',
                'db_table': 'encouragementType',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.DecimalField(decimal_places=0, max_digits=2)),
                ('lessonnum', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DecimalField(decimal_places=0, max_digits=1)),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.course')),
            ],
            options={
                'verbose_name': 'Lessons Journal',
                'verbose_name_plural': 'Lessons Journal',
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('lessonType', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Lesson Type',
                'verbose_name_plural': 'Lesson Types',
                'db_table': 'lessonType',
            },
        ),
        migrations.CreateModel(
            name='Milfaculty',
            fields=[
                ('milfaculty', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Military Faculty',
                'verbose_name_plural': 'Military Faculties',
                'db_table': 'milfaculty',
            },
        ),
        migrations.CreateModel(
            name='Milgroup',
            fields=[
                ('milgroup', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('milfaculty', models.ForeignKey(db_column='milfaculty', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.milfaculty')),
            ],
            options={
                'verbose_name': 'Military Group',
                'verbose_name_plural': 'Military Groups',
                'db_table': 'milgroup',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Place in Military Educational Centre',
                'verbose_name_plural': 'Places in Military Educational Centre',
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('program', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Educational Program',
                'verbose_name_plural': 'Educational Programs',
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='PunishmentType',
            fields=[
                ('punishmentType', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Punishment Type',
                'verbose_name_plural': 'Punishment Types',
                'db_table': 'punishmentType',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Military Rank',
                'verbose_name_plural': 'Military Ranks',
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Student Status',
                'verbose_name_plural': 'Student Statuses',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField()),
                ('photo', models.CharField(blank=True, max_length=128, null=True)),
                ('milgroup', models.ForeignKey(db_column='milgroup', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.milgroup')),
                ('program', models.ForeignKey(db_column='program', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.program')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.status')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentPost',
            fields=[
                ('studentPost', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Student Post',
                'verbose_name_plural': 'Student Posts',
                'db_table': 'studentPost',
            },
        ),
        migrations.CreateModel(
            name='TeacherPost',
            fields=[
                ('teacherPost', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Teacher Post',
                'verbose_name_plural': 'Teacher Posts',
                'db_table': 'teacherPost',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('milfaculty', models.ForeignKey(db_column='milfaculty', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.milfaculty')),
                ('milgroup', models.ForeignKey(blank=True, db_column='milgroup', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.milgroup')),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.teacherpost')),
                ('rank', models.ForeignKey(db_column='rank', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.rank')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('removedate', models.DateField(blank=True, null=True)),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
                ('teacherid', models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.teacher')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.punishmenttype')),
            ],
            options={
                'verbose_name': 'Punishment Journal',
                'verbose_name_plural': 'Punishment Journal',
                'db_table': 'punishment',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=0, max_digits=1)),
                ('controlform', models.ForeignKey(db_column='controlForm', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.controlform')),
                ('lessonid', models.ForeignKey(blank=True, db_column='lessonid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.lesson')),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
            ],
            options={
                'verbose_name': 'Marks Journal',
                'verbose_name_plural': 'Marks Journal',
                'db_table': 'mark',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='place',
            field=models.ForeignKey(db_column='place', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.place'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacherid',
            field=models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.lessontype'),
        ),
        migrations.CreateModel(
            name='Encouragement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
                ('teacherid', models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.teacher')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.encouragementtype')),
            ],
            options={
                'verbose_name': 'Encouragement Journal',
                'verbose_name_plural': 'Encouragement Journal',
                'db_table': 'encouragement',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.activitytype')),
            ],
            options={
                'verbose_name': 'Activity Journal',
                'verbose_name_plural': 'Activity Journal',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='StudentStudentpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentPost', models.ForeignKey(db_column='studentPost', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.studentpost')),
                ('studentid', models.OneToOneField(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
            ],
            options={
                'verbose_name': 'Student-Studentpost table',
                'verbose_name_plural': 'Student-Studentpost table',
                'db_table': 'student-studentpost',
                'unique_together': {('studentid', 'studentPost')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(db_column='skill', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.skill')),
                ('studentid', models.OneToOneField(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
            ],
            options={
                'verbose_name': 'Student-Skill table',
                'verbose_name_plural': 'Student-Skill table',
                'db_table': 'student-skill',
                'unique_together': {('studentid', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='LessonMilgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonid', models.OneToOneField(db_column='lessonid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.lesson')),
                ('milgroup', models.ForeignKey(db_column='milgroup', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.milgroup')),
            ],
            options={
                'verbose_name': 'Lesson-Milgroup table',
                'verbose_name_plural': 'Lesson-Milgroup table',
                'db_table': 'lesson-milgroup',
                'unique_together': {('lessonid', 'milgroup')},
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('absenceType', models.ForeignKey(db_column='absenceType', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.absencetype')),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to='mil_lms_backend.student')),
            ],
            options={
                'verbose_name': 'Absence Journal',
                'verbose_name_plural': 'Absence Journal',
                'db_table': 'absence',
                'unique_together': {('date', 'studentid')},
            },
        ),
    ]
