# Generated by Django 3.2.9 on 2021-11-06 18:46

import common.models.personal
import common.models.subjects
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=64, null=True)),
                ('place', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Birth Info',
                'verbose_name_plural': 'Birth Infos',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_phone_number', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Infos',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('MO', 'Москва'), ('SP', 'Санкт-Петербург'), ('NN', 'Нижний Новгород'), ('PE', 'Пермь')], max_length=2)),
                ('title', models.CharField(max_length=127)),
                ('abbreviation', models.CharField(blank=True, max_length=31)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'unique_together': {('campus', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Milspecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=31, unique=True)),
                ('available_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MO', 'Москва'), ('SP', 'Санкт-Петербург'), ('NN', 'Нижний Новгород'), ('PE', 'Пермь')], max_length=2), size=None)),
            ],
            options={
                'verbose_name': 'Military Specialty',
                'verbose_name_plural': 'Military Specialties',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=6)),
                ('ufms_name', models.CharField(max_length=255)),
                ('ufms_code', models.CharField(max_length=7)),
                ('issue_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passports',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=common.models.personal.upload_to)),
            ],
            options={
                'verbose_name': 'PersonPhoto',
                'verbose_name_plural': 'PersonPhoto',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=63)),
                ('title', models.CharField(max_length=127)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.faculty')),
            ],
            options={
                'verbose_name': 'Educational Program',
                'verbose_name_plural': 'Educational Programs',
            },
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32)),
                ('card_id', models.CharField(max_length=32)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.program')),
            ],
            options={
                'verbose_name': 'University Info',
                'verbose_name_plural': 'University Infos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('annotation', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=common.models.subjects.super_user_id, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(choices=[('FA', 'Отец'), ('MO', 'Мать'), ('BR', 'Брат'), ('SI', 'Сестра')], max_length=2)),
                ('citizenship', models.CharField(blank=True, max_length=64)),
                ('permanent_address', models.CharField(blank=True, max_length=128)),
                ('birth_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.birthinfo')),
                ('contact_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.contactinfo')),
            ],
            options={
                'verbose_name': 'Relative',
                'verbose_name_plural': 'Relatives',
            },
        ),
    ]
