# Generated by Django 3.2.10 on 2023-01-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='milspecialty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milspecialties', to='common.milspecialty'),
        ),
    ]
