# Generated by Django 3.1.5 on 2021-03-12 07:41

import common.models.persons
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=common.models.persons.upload_to)),
            ],
            options={
                'verbose_name': 'PersonPhoto',
                'verbose_name_plural': 'PersonPhoto',
            },
        ),
    ]
