# Generated by Django 3.2.10 on 2023-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_subject_milspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='available_to_choose_for_applicants',
            field=models.BooleanField(default=True),
        ),
    ]
