# Generated by Django 3.2.20 on 2024-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_program_available_to_choose_for_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocumentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=13)),
                ('insurance_number', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Personal Documents Info',
                'verbose_name_plural': 'Personal Documents Infos',
            },
        ),
    ]
