# Generated by Django 3.2.20 on 2023-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_program_available_to_choose_for_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='insurance_number',
            field=models.CharField(default='123-456-789 01', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='tax_id',
            field=models.CharField(default='771234567890', max_length=13),
            preserve_default=False,
        ),
    ]
