# Generated by Django 3.2.20 on 2024-10-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_personal_documents_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='milspecialty',
            name='selectable_by',
            field=models.ManyToManyField(to='common.Program'),
        ),
        migrations.AddField(
            model_name='milspecialty',
            name='selectable_by_every_program',
            field=models.BooleanField(default=True),
        ),
    ]
