# Generated by Django 3.2.20 on 2023-11-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_renamed_password_to_passworddata'),
        ('common', '0004_renamed_password_to_passworddata'),
        ('lms', '0008_renamed_password_to_passworddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
