# Generated by Django 3.2.20 on 2024-10-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_personal_documents_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='milspecialty',
            name='selectable_by_every_program',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MilspecialtySelectableByProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milspecialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.milspecialty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.program')),
            ],
            options={
                'verbose_name': 'Milspecialty selectable by program',
                'verbose_name_plural': 'Milspecialties selectable by programs',
            },
        ),
        migrations.AddField(
            model_name='milspecialty',
            name='selectable_by',
            field=models.ManyToManyField(through='common.MilspecialtySelectableByProgram', to='common.Program'),
        ),
        migrations.AddConstraint(
            model_name='milspecialtyselectablebyprogram',
            constraint=models.UniqueConstraint(fields=('milspecialty', 'program'), name='unique_milspecialty_selectable_by_program_relation'),
        ),
    ]
