# Generated by Django 3.2.20 on 2025-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_add_selectable_by_to_milspecs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Recruitment Office',
                'verbose_name_plural': 'Recruitment Offices',
            },
        ),
        migrations.AlterField(
            model_name='milspecialty',
            name='selectable_by',
            field=models.ManyToManyField(blank=True, to='common.Program'),
        ),
    ]
