# Generated by Django 3.2.20 on 2023-11-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_renamed_password_to_passworddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldocuments',
            options={'verbose_name': 'Personal Document', 'verbose_name_plural': 'Persona Documents'},
        ),
    ]
