# Generated by Django 3.2.20 on 2025-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_add_selectable_by_to_milspecs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Military Office',
                'verbose_name_plural': 'Military Offices',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='milspecialty',
            name='selectable_by',
            field=models.ManyToManyField(blank=True, to='common.Program'),
        ),
    ]
