# Generated by Django 3.2.20 on 2025-09-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_recruitment_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityinfo',
            name='graduation_year',
            field=models.IntegerField(default=None, null=True, verbose_name='Год окончания вуза'),
        ),
    ]
