# Generated by Django 3.1.2 on 2020-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='annotation',
            field=models.TextField(blank=True),
        ),
    ]
