# Generated by Django 3.1.1 on 2020-09-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_change_category_on_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='keywords',
            new_name='tags',
        ),
    ]
