# Generated by Django 3.1.3 on 2020-12-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('dms', '0002_make_document_title_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='common.Subject'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='common.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
