# Generated by Django 3.1.5 on 2021-01-27 18:20

from django.db import migrations, models
import django.db.models.deletion
import dms.models.books
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_auto_20201211_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=dms.models.books.upload_to)),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Covers',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.cover'),
        ),
    ]
