# Generated by Django 3.1.5 on 2021-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_add_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveSmallIntegerField(default=256),
            preserve_default=False,
        ),
    ]
