# Generated by Django 3.1.1 on 2020-09-19 17:26

from django.db import migrations, models
import django.db.models.deletion
import dms.models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_change_category_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.FileField(blank=True, upload_to=dms.models.upload_to)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.file'),
        ),
    ]
