# Generated by Django 3.1.5 on 2021-01-29 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_add_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='classmaterial',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='paper',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
