# Generated by Django 3.1.1 on 2020-09-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_add_file_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
