# Generated by Django 3.1.2 on 2020-11-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_user_reference_to_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dms.category'),
        ),
    ]
