# Generated by Django 3.1.2 on 2020-11-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_restrict_paper_delete_on_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='annotation',
            field=models.TextField(blank=True),
        ),
    ]
