# Generated by Django 3.2.3 on 2021-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('chat_id', models.PositiveBigIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot Auth Session',
                'verbose_name_plural': 'Telegram Bot Auth Sessions',
            },
        ),
    ]
