# Generated by Django 3.1.7 on 2021-04-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='code',
        ),
        migrations.AddField(
            model_name='session',
            name='phone',
            field=models.CharField(default=78005553535, max_length=32),
            preserve_default=False,
        ),
    ]
