# Generated by Django 2.1.7 on 2019-12-11 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('annotation', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='PublishPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Publish place',
                'verbose_name_plural': 'Publish places',
            },
        ),
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('annotation', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('abbreviation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.URLField(blank=True)),
                ('name', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='researches',
            name='authors',
            field=models.ManyToManyField(to='herokuapp.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='researches',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='researches',
            name='published_places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.PublishPlaces'),
        ),
        migrations.AddField(
            model_name='researches',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Status'),
        ),
        migrations.AddField(
            model_name='articles',
            name='authors',
            field=models.ManyToManyField(to='herokuapp.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='articles',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='articles',
            name='published_places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.PublishPlaces'),
        ),
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herokuapp.Status'),
        ),
    ]
