# Generated by Django 2.1.7 on 2019-11-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0003_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='published_places',
        ),
    ]
