# Generated by Django 2.1.7 on 2019-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0004_remove_documents_published_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Publish place',
                'verbose_name_plural': 'Publish places',
            },
        ),
    ]
