# Generated by Django 2.1.7 on 2019-11-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0005_publishplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='published_places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='herokuapp.PublishPlaces'),
            preserve_default=False,
        ),
    ]
