# Generated by Django 2.1.7 on 2019-12-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0006_documents_published_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('documents_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='herokuapp.Documents')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
            bases=('herokuapp.documents',),
        ),
    ]
