# Generated by Django 3.2.9 on 2022-02-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='name_genitive',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='patronymic_genitive',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicant',
            name='surname_genitive',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
