# Generated by Django 3.2.10 on 2023-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='mtc_admission_year',
            field=models.IntegerField(default=0),
        ),
    ]
