# Generated by Django 3.2.20 on 2023-11-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_renamed_password_to_passworddata'),
        ('ams', '0002_applicationprocess_mtc_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='common.personaldocuments'),
        ),
    ]
