# Generated by Django 3.2.20 on 2025-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20250321_1146'),
        ('ams', '0003_add_personal_documents_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='custom_military_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='military_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='common.militaryoffice'),
        ),
    ]
