# Generated by Django 3.2.20 on 2025-09-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_add_personal_documents_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(default='-', max_length=64, verbose_name='Национальность'),
        ),
    ]
