# Generated by Django 3.2.20 on 2025-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_add_nationality_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('UN', ''), ('SI', 'Холост'), ('MA', 'Женат')], default='UN', max_length=2),
        ),
    ]
