# Generated by Django 3.2.20 on 2026-02-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_add_martial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='endurance_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationprocess',
            name='speed_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationprocess',
            name='strength_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('PULL_UPS', 'Подтягивание на перекладине'), ('RUN_100', 'Бег на 100 м'), ('RUN_3K', 'Бег на 3 км')], max_length=32)),
                ('value', models.FloatField()),
                ('extra_params', models.JSONField(blank=True, default=dict)),
                ('secondary_score', models.SmallIntegerField(default=0)),
                ('application_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to='ams.applicationprocess')),
            ],
            options={
                'verbose_name': 'Exercise Result',
                'verbose_name_plural': 'Exercise Results',
                'unique_together': {('application_process', 'exercise_type')},
            },
        ),
    ]
