# Generated by Django 3.2.20 on 2026-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_applicant_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseresult',
            name='exercise_type',
            field=models.CharField(choices=[('PULL_UPS', 'Подтягивание на перекладине'), ('LIFT_TURNOVER', 'Подъем переворотом на перекладине'), ('LIFT_FORCE', 'Подъем силой на перекладине'), ('KETTLEBELL_SNATCH', 'Рывок гири'), ('RUN_60', 'Бег на 60 м'), ('RUN_100', 'Бег на 100 м'), ('SHUTTLE_RUN', 'Челночный бег 10×10 м'), ('RUN_1K', 'Бег на 1 км'), ('RUN_3K', 'Бег на 3 км')], max_length=32),
        ),
    ]
