from lms.models.students import Student


def get_students(users, milgroups, skills, programs):
    return [
        {
            "surname": "Ходилов",
            "name": "Борис",
            "patronymic": "Павлович",
            "user": users["bphodilov@mail.com"],
            "milgroup": milgroups["1801"],
            "contact_info": {
                "personal_phone_number": "79850000003",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-02-04",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Пушкина, дом 4",
            "personal_documents": {
                "series": "1112",
                "code": "111112",
                "ufms_name": "УФМС гор. Москва",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП1",
                "card_id": "СТДБ1",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Алексей",
            "patronymic": "Феликсович",
            "user": users["afhodilov@mail.com"],
            "milgroup": milgroups["1801"],
            "contact_info": {
                "personal_phone_number": "79850000004",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Футбол"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-12-25",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Пушкина, дом 2",
            "personal_documents": {
                "series": "1113",
                "code": "111113",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП2",
                "card_id": "СТДБ2",
            },
            "family": [],
        },
        {
            "surname": "Кретков",
            "name": "Павел",
            "patronymic": "Павлович",
            "user": users["ppkretkov@mail.com"],
            "milgroup": milgroups["1801"],
            "contact_info": {
                "personal_phone_number": "79850000005",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-02-15",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Флотская, дом 80",
            "personal_documents": {
                "series": "1114",
                "code": "111114",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП3",
                "card_id": "СТДБ3",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Павел",
            "patronymic": "Алексеевич",
            "user": users["patishanov@mail.com"],
            "milgroup": milgroups["1802"],
            "contact_info": {
                "personal_phone_number": "79850000006",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-07-05",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Солнечная, дом 6",
            "personal_documents": {
                "series": "1115",
                "code": "111115",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП4",
                "card_id": "СТДБ4",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Алексей",
            "patronymic": "Александрович",
            "user": users["aademchin@mail.com"],
            "milgroup": milgroups["1802"],
            "contact_info": {
                "personal_phone_number": "79850000007",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Футбол"], skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-04-17",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Ботаническая, дом 93",
            "personal_documents": {
                "series": "1116",
                "code": "111116",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП5",
                "card_id": "СТДБ5",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Дмитрий",
            "patronymic": "Феликсович",
            "user": users["dfdemchin@mail.com"],
            "milgroup": milgroups["1802"],
            "contact_info": {
                "personal_phone_number": "79850000008",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-01-19",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Пушкина, дом 73",
            "personal_documents": {
                "series": "1117",
                "code": "111117",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП6",
                "card_id": "СТДБ6",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Алексей",
            "patronymic": "Феликсович",
            "user": users["aftishanov@mail.com"],
            "milgroup": milgroups["1803"],
            "contact_info": {
                "personal_phone_number": "79850000009",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-08-05",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Электрозаводская, дом 24",
            "personal_documents": {
                "series": "1118",
                "code": "111118",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП7",
                "card_id": "СТДБ7",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Феликс",
            "patronymic": "Павлович",
            "user": users["fpdemchin@mail.com"],
            "milgroup": milgroups["1803"],
            "contact_info": {
                "personal_phone_number": "79850000010",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-04-04",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Петровка, дом 72",
            "personal_documents": {
                "series": "1119",
                "code": "111119",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП8",
                "card_id": "СТДБ8",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Дмитрий",
            "patronymic": "Дмитриевич",
            "user": users["ddtishanov@mail.com"],
            "milgroup": milgroups["1803"],
            "contact_info": {
                "personal_phone_number": "79850000011",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Гитара"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-09-20",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Пушкина, дом 65",
            "personal_documents": {
                "series": "1120",
                "code": "111120",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП9",
                "card_id": "СТДБ9",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Алексей",
            "patronymic": "Феликсович",
            "user": users["afdemchin@mail.com"],
            "milgroup": milgroups["1804"],
            "contact_info": {
                "personal_phone_number": "79850000012",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-05-06",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Ботаническая, дом 3",
            "personal_documents": {
                "series": "1121",
                "code": "111121",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП10",
                "card_id": "СТДБ10",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Феликс",
            "patronymic": "Павлович",
            "user": users["fptishanov@mail.com"],
            "milgroup": milgroups["1804"],
            "contact_info": {
                "personal_phone_number": "79850000013",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-10-22",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Солнечная, дом 31",
            "personal_documents": {
                "series": "1122",
                "code": "111122",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП11",
                "card_id": "СТДБ11",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Алексей",
            "patronymic": "Борисович",
            "user": users["abtishanov@mail.com"],
            "milgroup": milgroups["1804"],
            "contact_info": {
                "personal_phone_number": "79850000014",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-02-09",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Электрозаводская, дом 61",
            "personal_documents": {
                "series": "1123",
                "code": "111123",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП12",
                "card_id": "СТДБ12",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Дмитрий",
            "patronymic": "Алексеевич",
            "user": users["dahodilov@mail.com"],
            "milgroup": milgroups["1805"],
            "contact_info": {
                "personal_phone_number": "79850000015",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-04-16",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Флотская, дом 39",
            "personal_documents": {
                "series": "1124",
                "code": "111124",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП13",
                "card_id": "СТДБ13",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Борис",
            "patronymic": "Алексеевич",
            "user": users["bademchin@mail.com"],
            "milgroup": milgroups["1805"],
            "contact_info": {
                "personal_phone_number": "79850000016",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-11-25",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Солнечная, дом 71",
            "personal_documents": {
                "series": "1125",
                "code": "111125",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП14",
                "card_id": "СТДБ14",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Борис",
            "patronymic": "Павлович",
            "user": users["bptishanov@mail.com"],
            "milgroup": milgroups["1805"],
            "contact_info": {
                "personal_phone_number": "79850000017",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-05-25",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Солнечная, дом 49",
            "personal_documents": {
                "series": "1126",
                "code": "111126",
                "ufms_name": "УФМС гор. Москва",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП15",
                "card_id": "СТДБ15",
            },
            "family": [],
        },
        {
            "surname": "Кретков",
            "name": "Павел",
            "patronymic": "Александрович",
            "user": users["pakretkov@mail.com"],
            "milgroup": milgroups["1806"],
            "contact_info": {
                "personal_phone_number": "79850000018",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Гитара"], skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-03-08",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Архангельск, ул. Ботаническая, дом 75",
            "personal_documents": {
                "series": "1127",
                "code": "111127",
                "ufms_name": "УФМС гор. Архангельск",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП16",
                "card_id": "СТДБ16",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Александр",
            "patronymic": "Александрович",
            "user": users["aatishanov@mail.com"],
            "milgroup": milgroups["1806"],
            "contact_info": {
                "personal_phone_number": "79850000019",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-06-24",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Электрозаводская, дом 46",
            "personal_documents": {
                "series": "1128",
                "code": "111128",
                "ufms_name": "УФМС гор. Москва",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП17",
                "card_id": "СТДБ17",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Павел",
            "patronymic": "Борисович",
            "user": users["pbtishanov@mail.com"],
            "milgroup": milgroups["1806"],
            "contact_info": {
                "personal_phone_number": "79850000020",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Гитара"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-01-30",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Электрозаводская, дом 12",
            "personal_documents": {
                "series": "1129",
                "code": "111129",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП18",
                "card_id": "СТДБ18",
            },
            "family": [],
        },
        {
            "surname": "Кретков",
            "name": "Феликс",
            "patronymic": "Александрович",
            "user": users["fakretkov@mail.com"],
            "milgroup": milgroups["1807"],
            "contact_info": {
                "personal_phone_number": "79850000021",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-01-27",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Ботаническая, дом 97",
            "personal_documents": {
                "series": "1130",
                "code": "111130",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП19",
                "card_id": "СТДБ19",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Алексей",
            "patronymic": "Борисович",
            "user": users["abhodilov@mail.com"],
            "milgroup": milgroups["1807"],
            "contact_info": {
                "personal_phone_number": "79850000022",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-03-28",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Ботаническая, дом 94",
            "personal_documents": {
                "series": "1131",
                "code": "111131",
                "ufms_name": "УФМС гор. Москва",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП20",
                "card_id": "СТДБ20",
            },
            "family": [],
        },
        {
            "surname": "Закудряев",
            "name": "Борис",
            "patronymic": "Борисович",
            "user": users["bbzakudrjaev@mail.com"],
            "milgroup": milgroups["1807"],
            "contact_info": {
                "personal_phone_number": "79850000023",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Плавание"], skills["Футбол"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-09-30",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Флотская, дом 89",
            "personal_documents": {
                "series": "1132",
                "code": "111132",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП21",
                "card_id": "СТДБ21",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Феликс",
            "patronymic": "Александрович",
            "user": users["fademchin@mail.com"],
            "milgroup": milgroups["1808"],
            "contact_info": {
                "personal_phone_number": "79850000024",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-07-07",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Флотская, дом 97",
            "personal_documents": {
                "series": "1133",
                "code": "111133",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП22",
                "card_id": "СТДБ22",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Павел",
            "patronymic": "Павлович",
            "user": users["pptishanov@mail.com"],
            "milgroup": milgroups["1808"],
            "contact_info": {
                "personal_phone_number": "79850000025",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-11-19",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Флотская, дом 4",
            "personal_documents": {
                "series": "1134",
                "code": "111134",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП23",
                "card_id": "СТДБ23",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Дмитрий",
            "patronymic": "Павлович",
            "user": users["dphodilov@mail.com"],
            "milgroup": milgroups["1808"],
            "contact_info": {
                "personal_phone_number": "79850000026",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-07-08",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Электрозаводская, дом 2",
            "personal_documents": {
                "series": "1135",
                "code": "111135",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП24",
                "card_id": "СТДБ24",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Феликс",
            "patronymic": "Феликсович",
            "user": users["fftishanov@mail.com"],
            "milgroup": milgroups["1809"],
            "contact_info": {
                "personal_phone_number": "79850000027",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Футбол"], skills["Плавание"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-07-28",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Петровка, дом 72",
            "personal_documents": {
                "series": "1136",
                "code": "111136",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП25",
                "card_id": "СТДБ25",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Феликс",
            "patronymic": "Алексеевич",
            "user": users["fahodilov@mail.com"],
            "milgroup": milgroups["1809"],
            "contact_info": {
                "personal_phone_number": "79850000028",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Гитара"], skills["Футбол"], skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-04-18",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Электрозаводская, дом 2",
            "personal_documents": {
                "series": "1137",
                "code": "111137",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП26",
                "card_id": "СТДБ26",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Дмитрий",
            "patronymic": "Борисович",
            "user": users["dbdemchin@mail.com"],
            "milgroup": milgroups["1809"],
            "contact_info": {
                "personal_phone_number": "79850000029",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-07-11",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Академика Королева, дом 24",
            "personal_documents": {
                "series": "1138",
                "code": "111138",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП27",
                "card_id": "СТДБ27",
            },
            "family": [],
        },
        {
            "surname": "Закудряев",
            "name": "Алексей",
            "patronymic": "Борисович",
            "user": users["abzakudrjaev@mail.com"],
            "milgroup": milgroups["1810"],
            "contact_info": {
                "personal_phone_number": "79850000030",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-10-18",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Ботаническая, дом 44",
            "personal_documents": {
                "series": "1139",
                "code": "111139",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП28",
                "card_id": "СТДБ28",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Алексей",
            "patronymic": "Дмитриевич",
            "user": users["adhodilov@mail.com"],
            "milgroup": milgroups["1810"],
            "contact_info": {
                "personal_phone_number": "79850000031",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Гитара"], skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-05-09",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Барнаул, ул. Ботаническая, дом 26",
            "personal_documents": {
                "series": "1140",
                "code": "111140",
                "ufms_name": "УФМС гор. Барнаул",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП29",
                "card_id": "СТДБ29",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Феликс",
            "patronymic": "Феликсович",
            "user": users["ffdemchin@mail.com"],
            "milgroup": milgroups["1810"],
            "contact_info": {
                "personal_phone_number": "79850000032",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-03-15",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Архангельск, ул. Флотская, дом 26",
            "personal_documents": {
                "series": "1141",
                "code": "111141",
                "ufms_name": "УФМС гор. Архангельск",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП30",
                "card_id": "СТДБ30",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Борис",
            "patronymic": "Борисович",
            "user": users["bbtishanov@mail.com"],
            "milgroup": milgroups["1811"],
            "contact_info": {
                "personal_phone_number": "79850000033",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-04-22",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Ботаническая, дом 88",
            "personal_documents": {
                "series": "1142",
                "code": "111142",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП31",
                "card_id": "СТДБ31",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Борис",
            "patronymic": "Алексеевич",
            "user": users["bahodilov@mail.com"],
            "milgroup": milgroups["1811"],
            "contact_info": {
                "personal_phone_number": "79850000034",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Футбол"], skills["Гитара"], skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-11-14",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Флотская, дом 49",
            "personal_documents": {
                "series": "1143",
                "code": "111143",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП32",
                "card_id": "СТДБ32",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Александр",
            "patronymic": "Павлович",
            "user": users["aphodilov@mail.com"],
            "milgroup": milgroups["1811"],
            "contact_info": {
                "personal_phone_number": "79850000035",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-06-03",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Академика Королева, дом 92",
            "personal_documents": {
                "series": "1144",
                "code": "111144",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП33",
                "card_id": "СТДБ33",
            },
            "family": [],
        },
        {
            "surname": "Кретков",
            "name": "Борис",
            "patronymic": "Павлович",
            "user": users["bpkretkov@mail.com"],
            "milgroup": milgroups["1812"],
            "contact_info": {
                "personal_phone_number": "79850000036",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-01-11",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Дмитровская, дом 2",
            "personal_documents": {
                "series": "1145",
                "code": "111145",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП34",
                "card_id": "СТДБ34",
            },
            "family": [],
        },
        {
            "surname": "Закудряев",
            "name": "Феликс",
            "patronymic": "Алексеевич",
            "user": users["fazakudrjaev@mail.com"],
            "milgroup": milgroups["1812"],
            "contact_info": {
                "personal_phone_number": "79850000037",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-07-12",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Солнечная, дом 48",
            "personal_documents": {
                "series": "1146",
                "code": "111146",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП35",
                "card_id": "СТДБ35",
            },
            "family": [],
        },
        {
            "surname": "Закудряев",
            "name": "Дмитрий",
            "patronymic": "Александрович",
            "user": users["dazakudrjaev@mail.com"],
            "milgroup": milgroups["1812"],
            "contact_info": {
                "personal_phone_number": "79850000038",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Футбол"], skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-08-22",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Электрозаводская, дом 72",
            "personal_documents": {
                "series": "1147",
                "code": "111147",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП36",
                "card_id": "СТДБ36",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Борис",
            "patronymic": "Павлович",
            "user": users["bpdemchin@mail.com"],
            "milgroup": milgroups["1813"],
            "contact_info": {
                "personal_phone_number": "79850000039",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-06-16",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Флотская, дом 90",
            "personal_documents": {
                "series": "1148",
                "code": "111148",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП37",
                "card_id": "СТДБ37",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Павел",
            "patronymic": "Феликсович",
            "user": users["pfdemchin@mail.com"],
            "milgroup": milgroups["1813"],
            "contact_info": {
                "personal_phone_number": "79850000040",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-05-05",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Дмитровская, дом 48",
            "personal_documents": {
                "series": "1149",
                "code": "111149",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП38",
                "card_id": "СТДБ38",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Феликс",
            "patronymic": "Борисович",
            "user": users["fbdemchin@mail.com"],
            "milgroup": milgroups["1813"],
            "contact_info": {
                "personal_phone_number": "79850000041",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Гитара"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-01-20",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Петровка, дом 57",
            "personal_documents": {
                "series": "1150",
                "code": "111150",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП39",
                "card_id": "СТДБ39",
            },
            "family": [],
        },
        {
            "surname": "Кретков",
            "name": "Дмитрий",
            "patronymic": "Феликсович",
            "user": users["dfkretkov@mail.com"],
            "milgroup": milgroups["1814"],
            "contact_info": {
                "personal_phone_number": "79850000042",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Футбол"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-01-09",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Белгород, ул. Петровка, дом 89",
            "personal_documents": {
                "series": "1151",
                "code": "111151",
                "ufms_name": "УФМС гор. Белгород",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП40",
                "card_id": "СТДБ40",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Дмитрий",
            "patronymic": "Феликсович",
            "user": users["dftishanov@mail.com"],
            "milgroup": milgroups["1814"],
            "contact_info": {
                "personal_phone_number": "79850000043",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "2000-10-31",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Солнечная, дом 66",
            "personal_documents": {
                "series": "1152",
                "code": "111152",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП41",
                "card_id": "СТДБ41",
            },
            "family": [],
        },
        {
            "surname": "Тишанов",
            "name": "Феликс",
            "patronymic": "Дмитриевич",
            "user": users["fdtishanov@mail.com"],
            "milgroup": milgroups["1814"],
            "contact_info": {
                "personal_phone_number": "79850000044",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Гитара"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-04-29",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Барнаул, ул. Флотская, дом 73",
            "personal_documents": {
                "series": "1153",
                "code": "111153",
                "ufms_name": "УФМС гор. Барнаул",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП42",
                "card_id": "СТДБ42",
            },
            "family": [],
        },
        {
            "surname": "Демчин",
            "name": "Феликс",
            "patronymic": "Дмитриевич",
            "user": users["fddemchin@mail.com"],
            "milgroup": milgroups["1614"],
            "contact_info": {
                "personal_phone_number": "79850000045",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-05-15",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Астрахань, ул. Флотская, дом 4",
            "personal_documents": {
                "series": "1154",
                "code": "111154",
                "ufms_name": "УФМС гор. Астрахань",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП43",
                "card_id": "СТДБ43",
            },
            "family": [],
        },
        {
            "surname": "Ходилов",
            "name": "Феликс",
            "patronymic": "Феликсович",
            "user": users["ffhodilov@mail.com"],
            "milgroup": milgroups["1614"],
            "contact_info": {
                "personal_phone_number": "79850000046",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Гитара"], skills["Плавание"], skills["Футбол"]],
            "photo": None,
            "birth_info": {
                "date": "2000-12-09",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Санкт-Петербург, ул. Электрозаводская, дом 50",
            "personal_documents": {
                "series": "1155",
                "code": "111155",
                "ufms_name": "УФМС гор. Санкт-Петербург",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП44",
                "card_id": "СТДБ44",
            },
            "family": [],
        },
        {
            "surname": "Кретков",
            "name": "Алексей",
            "patronymic": "Алексеевич",
            "user": users["aakretkov@mail.com"],
            "milgroup": milgroups["1614"],
            "contact_info": {
                "personal_phone_number": "79850000047",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Футбол"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-05-31",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Биробиджан, ул. Пушкина, дом 51",
            "personal_documents": {
                "series": "1156",
                "code": "111156",
                "ufms_name": "УФМС гор. Биробиджан",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП45",
                "card_id": "СТДБ45",
            },
            "family": [],
        },
    ]
