from django.contrib.auth import get_user_model

from common.models.universities import (
    Program,
    UniversityInfo,
)
from common.models.personal import (
    ContactInfo,
    BirthInfo,
    Passport,
    Relative,
)

from common.utils.populate import get_or_create

from lms.models.common import Milgroup
from lms.models.students import (
    Skill,
    Student,
)


User = get_user_model()


def create_skills() -> dict[str, Skill]:
    skills = [
        {
            "title": "Футбол",
        },
        {
            "title": "Гитара",
        },
        {
            "title": "Плавание",
        },
    ]

    return {fields["title"]: get_or_create(Skill, **fields) for fields in skills}


def create_students(
    users: dict[str, User],
    milgroups: dict[str, Milgroup],
    skills: dict[str, Skill],
    programs: dict[str, Program],
) -> dict[str, Student]:
    # TODO(TmLev): Provide `family` for some students.

    students = [
        {
            "surname": "Хромов",
            "name": "Григорий",
            "patronymic": "Александрович",
            "user": users["gakhromov@mail.com"],
            "milgroup": milgroups["1809"],
            "contact_info": {
                "personal_phone_number": "70000000001",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Футбол"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "2000-11-04",
                "country": "Россия",
                "place": "Москва",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Пупкина, дом Кукушкина",
            "passport": {
                "series": "0000",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП00",
                "card_id": "СТДБ00",
            },
            "family": [],
        },
        {
            "surname": "Кацевалов",
            "name": "Артем",
            "patronymic": "Сергеевич",
            "user": users["askatsevalov@mail.com"],
            "milgroup": milgroups["1809"],
            "contact_info": {
                "personal_phone_number": "70000000002",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"]],
            "photo": None,
            "birth_info": {
                "date": "2000-02-23",
                "country": "Украина",
                "place": "Донбасс",
            },
            "citizenship": "Подольск",
            "permanent_address": "г. Подольск, ул. Кац, дом Цак",
            "passport": {
                "series": "1111",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП01",
                "card_id": "СТДБ01",
            },
            "family": [],
        },
        {
            "surname": "Исаков",
            "name": "Владислав",
            "patronymic": "Евгеньевич",
            "user": users["veisakov@mail.com"],
            "milgroup": milgroups["1809"],
            "contact_info": {
                "personal_phone_number": "70000000003",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Футбол"], skills["Плавание"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "1999-08-29",
                "country": "Россия",
                "place": "Челябинск",
            },
            "passport": {
                "series": "2222",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Волжский, ул. Плаксина, дом Какуна",
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП02",
                "card_id": "СТДБ02",
            },
            "family": [],
        },
        {
            "surname": "Алиев",
            "name": "Насир",
            "patronymic": "Ашурович",
            "user": users["naaliev@mail.com"],
            "milgroup": milgroups["1808"],
            "contact_info": {
                "personal_phone_number": "70000000004",
            },
            "status": Student.Status.STUDYING.value,
            "post": None,
            "skills": [skills["Футбол"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "1999-05-04",
                "country": "Дагестан",
                "place": "Махачкала",
            },
            "citizenship": "Дагестан",
            "permanent_address": "г. Махачкала, ул. Рамзана Кадырова, дом 228",
            "passport": {
                "series": "3333",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП03",
                "card_id": "СТДБ03",
            },
            "family": [],
        },
        {
            "surname": "Куркин",
            "name": "Андрей",
            "patronymic": "Витальевич",
            "user": users["avkurkin@mail.com"],
            "milgroup": milgroups["1812"],
            "contact_info": {
                "personal_phone_number": "70000000005",
            },
            "status": Student.Status.STUDYING.value,
            "post": Student.Post.MILGROUP_COMMANDER.value,
            "skills": [skills["Плавание"], skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "1999-11-12",
                "country": "Россия",
                "place": "Тверь",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Пупкина, дом Кукушкина",
            "passport": {
                "series": "4444",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП04",
                "card_id": "СТДБ04",
            },
            "family": [],
        },
        {
            "surname": "Иванов",
            "name": "Петр",
            "patronymic": "Сидорович",
            "user": users["psivanov@mail.com"],
            "milgroup": milgroups["1804"],
            "contact_info": {
                "personal_phone_number": "70000000006",
            },
            "status": Student.Status.EXPELLED.value,
            "post": Student.Post.MILSQUAD_COMMANDER.value,
            "skills": [skills["Гитара"]],
            "photo": None,
            "birth_info": {
                "date": "1999-05-04",
                "country": "Литва",
                "place": "Литвения",
            },
            "citizenship": "РФ",
            "permanent_address": "г. Москва, ул. Пупкина, дом Кукушкина",
            "passport": {
                "series": "5555",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП05",
                "card_id": "СТДБ05",
            },
            "family": [],
        },
        {
            "surname": "Чукмарикадзе",
            "name": "Губарибек",
            "patronymic": "Алкинбеков",
            "user": None,
            "milgroup": milgroups["1612"],
            "contact_info": {
                "personal_phone_number": "70000000007",
            },
            "status": Student.Status.GRADUATED.value,
            "post": None,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "1998-10-11",
                "country": "Германия",
                "place": "Мюнхен",
            },
            "citizenship": "Узбекистан",
            "permanent_address": "г. Москва, ул. Пупкина, дом Кукушкина",
            "passport": {
                "series": "6666",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП06",
                "card_id": "СТДБ06",
            },
            "family": [],
        },
        {
            "surname": "Харламов",
            "name": "Денис",
            "patronymic": "",
            "user": None,
            "milgroup": milgroups["1612"],
            "contact_info": {
                "personal_phone_number": "70000000008",
            },
            "status": Student.Status.EXPELLED.value,
            "post": None,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "1969-04-12",
                "country": "Швейцария",
                "place": "Цюрих",
            },
            "citizenship": "Узбекистан",
            "permanent_address": "г. Москва, ул. Пупкина, дом Кукушкина",
            "passport": {
                "series": "7777",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП07",
                "card_id": "СТДБ07",
            },
            "family": [],
        },
        {
            "surname": "Коронов",
            "name": "Илья",
            "patronymic": "Ахмат оглы",
            "user": None,
            "milgroup": milgroups["1612"],
            "contact_info": {
                "personal_phone_number": "70000000009",
            },
            "status": Student.Status.GRADUATED.value,
            "post": None,
            "skills": [],
            "photo": None,
            "birth_info": {
                "date": "1995-06-23",
                "country": "Беларусь",
                "place": "Минск",
            },
            "citizenship": "Узбекистан",
            "permanent_address": "г. Москва, ул. Пупкина, дом Кукушкина",
            "passport": {
                "series": "8888",
                "code": "111111",
                "ufms_name": "УФМС гор. Москвы",
                "ufms_code": "740-056",
                "issue_date": "2020-10-02",
            },
            "recruitment_office": "Московский военкомат",
            "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП08",
                "card_id": "СТДБ08",
            },
            "family": [],
        },
    # Generate
    {
        "surname": "Закудряев",
        "name": "Борис",
        "patronymic": "Александрович",
        "user": users["baZakudrjaev@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000003",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Плавание"], skills["Футбол"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-30",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Санкт-Петербург, ул. Флотская, дом 94",
        "passport": {
            "series": "1112",
            "code": "111112",
            "ufms_name": "УФМС гор. Санкт-Петербург",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП1",
                "card_id": "СТДБ1",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Дмитрий",
        "patronymic": "Александрович",
        "user": users["daDemchin@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000004",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Плавание"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-04-10",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Флотская, дом 63",
        "passport": {
            "series": "1113",
            "code": "111113",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП2",
                "card_id": "СТДБ2",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Алексей",
        "patronymic": "Александрович",
        "user": users["aaTishanov@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000005",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-02-19",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Академика Королева, дом 38",
        "passport": {
            "series": "1114",
            "code": "111114",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП3",
                "card_id": "СТДБ3",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Дмитрий",
        "patronymic": "Флексеевич",
        "user": users["dfZakudrjaev@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000006",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-01-05",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Академика Королева, дом 25",
        "passport": {
            "series": "1115",
            "code": "111115",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП4",
                "card_id": "СТДБ4",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Александр",
        "patronymic": "Александрович",
        "user": users["aaZakudrjaev@mail.com"],
        "milgroup": milgroups["1802"],
        "contact_info": {
            "personal_phone_number": "79850000007",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-11-25",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Дмитровская, дом 11",
        "passport": {
            "series": "1116",
            "code": "111116",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП5",
                "card_id": "СТДБ5",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Алексей",
        "patronymic": "Борисович",
        "user": users["abHodilov@mail.com"],
        "milgroup": milgroups["1802"],
        "contact_info": {
            "personal_phone_number": "79850000008",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Плавание"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-06-08",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Санкт-Петербург, ул. Пушкина, дом 51",
        "passport": {
            "series": "1117",
            "code": "111117",
            "ufms_name": "УФМС гор. Санкт-Петербург",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП6",
                "card_id": "СТДБ6",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Дмитрий",
        "patronymic": "Павлович",
        "user": users["dpZakudrjaev@mail.com"],
        "milgroup": milgroups["1802"],
        "contact_info": {
            "personal_phone_number": "79850000009",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-24",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Академика Королева, дом 53",
        "passport": {
            "series": "1118",
            "code": "111118",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП7",
                "card_id": "СТДБ7",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Фелекс",
        "patronymic": "Борисович",
        "user": users["fbDemchin@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000011",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-11-07",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Солнечная, дом 37",
        "passport": {
            "series": "1120",
            "code": "111120",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП9",
                "card_id": "СТДБ9",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Алексей",
        "patronymic": "Флексеевич",
        "user": users["afTishanov@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000012",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-06-27",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Академика Королева, дом 95",
        "passport": {
            "series": "1121",
            "code": "111121",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП10",
                "card_id": "СТДБ10",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Борис",
        "patronymic": "Алексеевич",
        "user": users["baDemchin@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000013",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-01",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Ботаническая, дом 12",
        "passport": {
            "series": "1122",
            "code": "111122",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП11",
                "card_id": "СТДБ11",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Фелекс",
        "patronymic": "Борисович",
        "user": users["fbHodilov@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000014",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-04-07",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Солнечная, дом 25",
        "passport": {
            "series": "1123",
            "code": "111123",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП12",
                "card_id": "СТДБ12",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Паша",
        "patronymic": "Борисович",
        "user": users["pbHodilov@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000015",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-13",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Флотская, дом 6",
        "passport": {
            "series": "1124",
            "code": "111124",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП13",
                "card_id": "СТДБ13",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Фелекс",
        "patronymic": "Дмитриевич",
        "user": users["fdZakudrjaev@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000016",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-10-27",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Ботаническая, дом 31",
        "passport": {
            "series": "1125",
            "code": "111125",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП14",
                "card_id": "СТДБ14",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Алексей",
        "patronymic": "Борисович",
        "user": users["abDemchin@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000017",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-03-18",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Пушкина, дом 8",
        "passport": {
            "series": "1126",
            "code": "111126",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП15",
                "card_id": "СТДБ15",
            },
        "family": [],
    },
{
        "surname": "Кретков",
        "name": "Александр",
        "patronymic": "Дмитриевич",
        "user": users["adKretkov@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000018",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-05-22",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Петровка, дом 73",
        "passport": {
            "series": "1127",
            "code": "111127",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП16",
                "card_id": "СТДБ16",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Борис",
        "patronymic": "Флексеевич",
        "user": users["bfZakudrjaev@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000019",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-12-27",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Электрозаводская, дом 54",
        "passport": {
            "series": "1128",
            "code": "111128",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП17",
                "card_id": "СТДБ17",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Борис",
        "patronymic": "Борисович",
        "user": users["bbTishanov@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000020",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-11-26",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Санкт-Петербург, ул. Ботаническая, дом 93",
        "passport": {
            "series": "1129",
            "code": "111129",
            "ufms_name": "УФМС гор. Санкт-Петербург",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП18",
                "card_id": "СТДБ18",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Дмитрий",
        "patronymic": "Александрович",
        "user": users["daTishanov@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000021",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Плавание"], skills["Футбол"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-08-07",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Флотская, дом 63",
        "passport": {
            "series": "1130",
            "code": "111130",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП19",
                "card_id": "СТДБ19",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Дмитрий",
        "patronymic": "Борисович",
        "user": users["dbTishanov@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000022",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-11-18",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Электрозаводская, дом 75",
        "passport": {
            "series": "1131",
            "code": "111131",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП20",
                "card_id": "СТДБ20",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Александр",
        "patronymic": "Алексеевич",
        "user": users["aaDemchin@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000023",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"], skills["Футбол"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-12",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Петровка, дом 56",
        "passport": {
            "series": "1132",
            "code": "111132",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП21",
                "card_id": "СТДБ21",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Фелекс",
        "patronymic": "Павлович",
        "user": users["fpDemchin@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000024",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-02-04",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Петровка, дом 99",
        "passport": {
            "series": "1133",
            "code": "111133",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП22",
                "card_id": "СТДБ22",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Паша",
        "patronymic": "Алексеевич",
        "user": users["paHodilov@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000025",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"], skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-05",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Флотская, дом 89",
        "passport": {
            "series": "1134",
            "code": "111134",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП23",
                "card_id": "СТДБ23",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Паша",
        "patronymic": "Александрович",
        "user": users["paDemchin@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000026",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"], skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-05-26",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Академика Королева, дом 25",
        "passport": {
            "series": "1135",
            "code": "111135",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП24",
                "card_id": "СТДБ24",
            },
        "family": [],
    },

    ]

    objects = {}

    for fields in students:
        fields["contact_info"] = get_or_create(
            ContactInfo,
            **fields.pop("contact_info"),
        )
        fields["birth_info"] = BirthInfo.objects.create(**fields.pop("birth_info"),)
        
        fields["passport"] = get_or_create(
            Passport,
            **fields.pop("passport"),
        )
        fields["university_info"] = get_or_create(
            UniversityInfo,
            **fields.pop("university_info"),
        )

        skills = fields.pop("skills")
        family = [
            get_or_create(Relative, **relative_fields)
            for relative_fields in fields.pop("family")
        ]

        object_ = get_or_create(Student, **fields)

        object_.skills.add(*skills)
        object_.family.add(*family)
        object_.save()

        objects[fields["surname"]] = object_

    return objects
