from lms.models.students import Student


def get_students(users, milgroups, skills, programs):
    return [

{
        "surname": "Закудряев",
        "name": "Алексей",
        "patronymic": "Александрович",
        "user": users["aazakudrjaev@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000003",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-08-31",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Пушкина, дом 85",
        "passport": {
            "series": "1112",
            "code": "111112",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП1",
                "card_id": "СТДБ1",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Феликс",
        "patronymic": "Феликсович",
        "user": users["fftishanov@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000004",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Футбол"], skills["Плавание"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-07-29",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Петровка, дом 23",
        "passport": {
            "series": "1113",
            "code": "111113",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП2",
                "card_id": "СТДБ2",
            },
        "family": [],
    },
{
        "surname": "Кретков",
        "name": "Феликс",
        "patronymic": "Павлович",
        "user": users["fpkretkov@mail.com"],
        "milgroup": milgroups["1801"],
        "contact_info": {
            "personal_phone_number": "79850000005",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-25",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Электрозаводская, дом 89",
        "passport": {
            "series": "1114",
            "code": "111114",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП3",
                "card_id": "СТДБ3",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Павел",
        "patronymic": "Алексеевич",
        "user": users["pademchin@mail.com"],
        "milgroup": milgroups["1802"],
        "contact_info": {
            "personal_phone_number": "79850000006",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-23",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Барнаул, ул. Академика Королева, дом 34",
        "passport": {
            "series": "1115",
            "code": "111115",
            "ufms_name": "УФМС гор. Барнаул",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП4",
                "card_id": "СТДБ4",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Павел",
        "patronymic": "Дмитриевич",
        "user": users["pddemchin@mail.com"],
        "milgroup": milgroups["1802"],
        "contact_info": {
            "personal_phone_number": "79850000007",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Плавание"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-11",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Дмитровская, дом 54",
        "passport": {
            "series": "1116",
            "code": "111116",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП5",
                "card_id": "СТДБ5",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Борис",
        "patronymic": "Борисович",
        "user": users["bbtishanov@mail.com"],
        "milgroup": milgroups["1802"],
        "contact_info": {
            "personal_phone_number": "79850000008",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-07-30",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Петровка, дом 39",
        "passport": {
            "series": "1117",
            "code": "111117",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП6",
                "card_id": "СТДБ6",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Феликс",
        "patronymic": "Александрович",
        "user": users["fatishanov@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000009",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-29",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Барнаул, ул. Дмитровская, дом 64",
        "passport": {
            "series": "1118",
            "code": "111118",
            "ufms_name": "УФМС гор. Барнаул",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП7",
                "card_id": "СТДБ7",
            },
        "family": [],
    },
{
        "surname": "Кретков",
        "name": "Александр",
        "patronymic": "Павлович",
        "user": users["apkretkov@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000010",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-05-23",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Ботаническая, дом 38",
        "passport": {
            "series": "1119",
            "code": "111119",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП8",
                "card_id": "СТДБ8",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Борис",
        "patronymic": "Александрович",
        "user": users["bademchin@mail.com"],
        "milgroup": milgroups["1803"],
        "contact_info": {
            "personal_phone_number": "79850000011",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"], skills["Плавание"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-11-14",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Солнечная, дом 78",
        "passport": {
            "series": "1120",
            "code": "111120",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП9",
                "card_id": "СТДБ9",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Алексей",
        "patronymic": "Александрович",
        "user": users["aademchin@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000012",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-08-11",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Электрозаводская, дом 50",
        "passport": {
            "series": "1121",
            "code": "111121",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП10",
                "card_id": "СТДБ10",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Павел",
        "patronymic": "Александрович",
        "user": users["pazakudrjaev@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000013",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-03-22",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Ботаническая, дом 78",
        "passport": {
            "series": "1122",
            "code": "111122",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП11",
                "card_id": "СТДБ11",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Феликс",
        "patronymic": "Александрович",
        "user": users["fazakudrjaev@mail.com"],
        "milgroup": milgroups["1804"],
        "contact_info": {
            "personal_phone_number": "79850000014",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Футбол"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-07-22",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Дмитровская, дом 61",
        "passport": {
            "series": "1123",
            "code": "111123",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП12",
                "card_id": "СТДБ12",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Феликс",
        "patronymic": "Павлович",
        "user": users["fpzakudrjaev@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000015",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-12-11",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Дмитровская, дом 53",
        "passport": {
            "series": "1124",
            "code": "111124",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП13",
                "card_id": "СТДБ13",
            },
        "family": [],
    },
{
        "surname": "Кретков",
        "name": "Павел",
        "patronymic": "Алексеевич",
        "user": users["pakretkov@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000016",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Плавание"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-04-23",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Флотская, дом 77",
        "passport": {
            "series": "1125",
            "code": "111125",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП14",
                "card_id": "СТДБ14",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Павел",
        "patronymic": "Алексеевич",
        "user": users["patishanov@mail.com"],
        "milgroup": milgroups["1805"],
        "contact_info": {
            "personal_phone_number": "79850000017",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-08-27",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Ботаническая, дом 73",
        "passport": {
            "series": "1126",
            "code": "111126",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП15",
                "card_id": "СТДБ15",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Алексей",
        "patronymic": "Феликсович",
        "user": users["aftishanov@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000018",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-08-10",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Солнечная, дом 54",
        "passport": {
            "series": "1127",
            "code": "111127",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП16",
                "card_id": "СТДБ16",
            },
        "family": [],
    },
{
        "surname": "Кретков",
        "name": "Феликс",
        "patronymic": "Феликсович",
        "user": users["ffkretkov@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000019",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-04-11",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Пушкина, дом 68",
        "passport": {
            "series": "1128",
            "code": "111128",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП17",
                "card_id": "СТДБ17",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Алексей",
        "patronymic": "Алексеевич",
        "user": users["aahodilov@mail.com"],
        "milgroup": milgroups["1806"],
        "contact_info": {
            "personal_phone_number": "79850000020",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-03-29",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Барнаул, ул. Ботаническая, дом 74",
        "passport": {
            "series": "1129",
            "code": "111129",
            "ufms_name": "УФМС гор. Барнаул",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП18",
                "card_id": "СТДБ18",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Дмитрий",
        "patronymic": "Павлович",
        "user": users["dpdemchin@mail.com"],
        "milgroup": milgroups["1807"],
        "contact_info": {
            "personal_phone_number": "79850000021",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-10-11",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Пушкина, дом 34",
        "passport": {
            "series": "1130",
            "code": "111130",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП19",
                "card_id": "СТДБ19",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Алексей",
        "patronymic": "Борисович",
        "user": users["abhodilov@mail.com"],
        "milgroup": milgroups["1807"],
        "contact_info": {
            "personal_phone_number": "79850000022",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-11-03",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Пушкина, дом 100",
        "passport": {
            "series": "1131",
            "code": "111131",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП20",
                "card_id": "СТДБ20",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Дмитрий",
        "patronymic": "Алексеевич",
        "user": users["dademchin@mail.com"],
        "milgroup": milgroups["1807"],
        "contact_info": {
            "personal_phone_number": "79850000023",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-08-12",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Пушкина, дом 66",
        "passport": {
            "series": "1132",
            "code": "111132",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП21",
                "card_id": "СТДБ21",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Борис",
        "patronymic": "Павлович",
        "user": users["bpzakudrjaev@mail.com"],
        "milgroup": milgroups["1808"],
        "contact_info": {
            "personal_phone_number": "79850000024",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"], skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-02",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Санкт-Петербург, ул. Пушкина, дом 6",
        "passport": {
            "series": "1133",
            "code": "111133",
            "ufms_name": "УФМС гор. Санкт-Петербург",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП22",
                "card_id": "СТДБ22",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Алексей",
        "patronymic": "Павлович",
        "user": users["apzakudrjaev@mail.com"],
        "milgroup": milgroups["1808"],
        "contact_info": {
            "personal_phone_number": "79850000025",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-07-08",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Академика Королева, дом 70",
        "passport": {
            "series": "1134",
            "code": "111134",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП23",
                "card_id": "СТДБ23",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Борис",
        "patronymic": "Александрович",
        "user": users["bahodilov@mail.com"],
        "milgroup": milgroups["1808"],
        "contact_info": {
            "personal_phone_number": "79850000026",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-04-26",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Москва, ул. Солнечная, дом 58",
        "passport": {
            "series": "1135",
            "code": "111135",
            "ufms_name": "УФМС гор. Москва",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Экономика"],
                "group": "ГРПП24",
                "card_id": "СТДБ24",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Борис",
        "patronymic": "Дмитриевич",
        "user": users["bdtishanov@mail.com"],
        "milgroup": milgroups["1809"],
        "contact_info": {
            "personal_phone_number": "79850000027",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Плавание"], skills["Футбол"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-05-22",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Петровка, дом 89",
        "passport": {
            "series": "1136",
            "code": "111136",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП25",
                "card_id": "СТДБ25",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Борис",
        "patronymic": "Александрович",
        "user": users["batishanov@mail.com"],
        "milgroup": milgroups["1809"],
        "contact_info": {
            "personal_phone_number": "79850000028",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-10-20",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Санкт-Петербург, ул. Пушкина, дом 74",
        "passport": {
            "series": "1137",
            "code": "111137",
            "ufms_name": "УФМС гор. Санкт-Петербург",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП26",
                "card_id": "СТДБ26",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Павел",
        "patronymic": "Борисович",
        "user": users["pbdemchin@mail.com"],
        "milgroup": milgroups["1809"],
        "contact_info": {
            "personal_phone_number": "79850000029",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-02-12",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Барнаул, ул. Флотская, дом 25",
        "passport": {
            "series": "1138",
            "code": "111138",
            "ufms_name": "УФМС гор. Барнаул",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП27",
                "card_id": "СТДБ27",
            },
        "family": [],
    },
{
        "surname": "Кретков",
        "name": "Алексей",
        "patronymic": "Александрович",
        "user": users["aakretkov@mail.com"],
        "milgroup": milgroups["1810"],
        "contact_info": {
            "personal_phone_number": "79850000030",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-06",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Солнечная, дом 2",
        "passport": {
            "series": "1139",
            "code": "111139",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП28",
                "card_id": "СТДБ28",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Павел",
        "patronymic": "Феликсович",
        "user": users["pfhodilov@mail.com"],
        "milgroup": milgroups["1810"],
        "contact_info": {
            "personal_phone_number": "79850000031",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Футбол"], skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-03",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Барнаул, ул. Петровка, дом 48",
        "passport": {
            "series": "1140",
            "code": "111140",
            "ufms_name": "УФМС гор. Барнаул",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП29",
                "card_id": "СТДБ29",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Александр",
        "patronymic": "Феликсович",
        "user": users["afdemchin@mail.com"],
        "milgroup": milgroups["1810"],
        "contact_info": {
            "personal_phone_number": "79850000032",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-27",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Санкт-Петербург, ул. Электрозаводская, дом 22",
        "passport": {
            "series": "1141",
            "code": "111141",
            "ufms_name": "УФМС гор. Санкт-Петербург",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП30",
                "card_id": "СТДБ30",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Павел",
        "patronymic": "Дмитриевич",
        "user": users["pdhodilov@mail.com"],
        "milgroup": milgroups["1811"],
        "contact_info": {
            "personal_phone_number": "79850000033",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-05-17",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Ботаническая, дом 45",
        "passport": {
            "series": "1142",
            "code": "111142",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП31",
                "card_id": "СТДБ31",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Павел",
        "patronymic": "Борисович",
        "user": users["pbhodilov@mail.com"],
        "milgroup": milgroups["1811"],
        "contact_info": {
            "personal_phone_number": "79850000034",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Футбол"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-07-30",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Петровка, дом 60",
        "passport": {
            "series": "1143",
            "code": "111143",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП32",
                "card_id": "СТДБ32",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Александр",
        "patronymic": "Дмитриевич",
        "user": users["adhodilov@mail.com"],
        "milgroup": milgroups["1811"],
        "contact_info": {
            "personal_phone_number": "79850000035",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-10-12",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Электрозаводская, дом 15",
        "passport": {
            "series": "1144",
            "code": "111144",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП33",
                "card_id": "СТДБ33",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Александр",
        "patronymic": "Дмитриевич",
        "user": users["adzakudrjaev@mail.com"],
        "milgroup": milgroups["1812"],
        "contact_info": {
            "personal_phone_number": "79850000036",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Футбол"], skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-23",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Дмитровская, дом 13",
        "passport": {
            "series": "1145",
            "code": "111145",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП34",
                "card_id": "СТДБ34",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Борис",
        "patronymic": "Борисович",
        "user": users["bbhodilov@mail.com"],
        "milgroup": milgroups["1812"],
        "contact_info": {
            "personal_phone_number": "79850000037",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-08-03",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Петровка, дом 61",
        "passport": {
            "series": "1146",
            "code": "111146",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП35",
                "card_id": "СТДБ35",
            },
        "family": [],
    },
{
        "surname": "Закудряев",
        "name": "Александр",
        "patronymic": "Феликсович",
        "user": users["afzakudrjaev@mail.com"],
        "milgroup": milgroups["1812"],
        "contact_info": {
            "personal_phone_number": "79850000038",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-03-12",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Академика Королева, дом 90",
        "passport": {
            "series": "1147",
            "code": "111147",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП36",
                "card_id": "СТДБ36",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Дмитрий",
        "patronymic": "Павлович",
        "user": users["dphodilov@mail.com"],
        "milgroup": milgroups["1813"],
        "contact_info": {
            "personal_phone_number": "79850000039",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Плавание"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-09-01",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Дмитровская, дом 3",
        "passport": {
            "series": "1148",
            "code": "111148",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП37",
                "card_id": "СТДБ37",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Павел",
        "patronymic": "Алексеевич",
        "user": users["pahodilov@mail.com"],
        "milgroup": milgroups["1813"],
        "contact_info": {
            "personal_phone_number": "79850000040",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-01-02",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Электрозаводская, дом 31",
        "passport": {
            "series": "1149",
            "code": "111149",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП38",
                "card_id": "СТДБ38",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Борис",
        "patronymic": "Дмитриевич",
        "user": users["bdhodilov@mail.com"],
        "milgroup": milgroups["1813"],
        "contact_info": {
            "personal_phone_number": "79850000041",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Плавание"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-11",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Солнечная, дом 34",
        "passport": {
            "series": "1150",
            "code": "111150",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информационная безопасность"],
                "group": "ГРПП39",
                "card_id": "СТДБ39",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Феликс",
        "patronymic": "Павлович",
        "user": users["fptishanov@mail.com"],
        "milgroup": milgroups["1814"],
        "contact_info": {
            "personal_phone_number": "79850000042",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-12-30",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Астрахань, ул. Пушкина, дом 88",
        "passport": {
            "series": "1151",
            "code": "111151",
            "ufms_name": "УФМС гор. Астрахань",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Программная инженерия"],
                "group": "ГРПП40",
                "card_id": "СТДБ40",
            },
        "family": [],
    },
{
        "surname": "Ходилов",
        "name": "Алексей",
        "patronymic": "Павлович",
        "user": users["aphodilov@mail.com"],
        "milgroup": milgroups["1814"],
        "contact_info": {
            "personal_phone_number": "79850000043",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Гитара"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-03-25",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Электрозаводская, дом 4",
        "passport": {
            "series": "1152",
            "code": "111152",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП41",
                "card_id": "СТДБ41",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Алексей",
        "patronymic": "Павлович",
        "user": users["aptishanov@mail.com"],
        "milgroup": milgroups["1814"],
        "contact_info": {
            "personal_phone_number": "79850000044",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [skills["Гитара"], skills["Плавание"], skills["Футбол"]],
        "photo": None,
        "birth_info": {
            "date": "2000-12-01",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Архангельск, ул. Ботаническая, дом 92",
        "passport": {
            "series": "1153",
            "code": "111153",
            "ufms_name": "УФМС гор. Архангельск",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП42",
                "card_id": "СТДБ42",
            },
        "family": [],
    },
{
        "surname": "Демчин",
        "name": "Алексей",
        "patronymic": "Павлович",
        "user": users["apdemchin@mail.com"],
        "milgroup": milgroups["1614"],
        "contact_info": {
            "personal_phone_number": "79850000045",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILGROUP_COMMANDER.value,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-05-30",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Белгород, ул. Академика Королева, дом 30",
        "passport": {
            "series": "1154",
            "code": "111154",
            "ufms_name": "УФМС гор. Белгород",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП43",
                "card_id": "СТДБ43",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Павел",
        "patronymic": "Феликсович",
        "user": users["pftishanov@mail.com"],
        "milgroup": milgroups["1614"],
        "contact_info": {
            "personal_phone_number": "79850000046",
        },
        "status": Student.Status.STUDYING.value,
        "post": None,
        "skills": [],
        "photo": None,
        "birth_info": {
            "date": "2000-06-25",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Барнаул, ул. Ботаническая, дом 7",
        "passport": {
            "series": "1155",
            "code": "111155",
            "ufms_name": "УФМС гор. Барнаул",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Юриспруденция"],
                "group": "ГРПП44",
                "card_id": "СТДБ44",
            },
        "family": [],
    },
{
        "surname": "Тишанов",
        "name": "Александр",
        "patronymic": "Алексеевич",
        "user": users["aatishanov@mail.com"],
        "milgroup": milgroups["1614"],
        "contact_info": {
            "personal_phone_number": "79850000047",
        },
        "status": Student.Status.STUDYING.value,
        "post": Student.Post.MILSQUAD_COMMANDER.value,
        "skills": [skills["Плавание"], skills["Гитара"]],
        "photo": None,
        "birth_info": {
            "date": "2000-06-16",
            "country": "Россия",
            "place": "Москва",
        },
        "citizenship": "РФ",
        "permanent_address": "г. Биробиджан, ул. Флотская, дом 20",
        "passport": {
            "series": "1156",
            "code": "111156",
            "ufms_name": "УФМС гор. Биробиджан",
            "ufms_code": "740-056",
            "issue_date": "2020-10-02",
        },
        "recruitment_office": "Московский военкомат",
        "university_info": {
                "program": programs["Информатика и вычислительная техника"],
                "group": "ГРПП45",
                "card_id": "СТДБ45",
            },
        "family": [],
    },
]
