# Generated by Django 3.2.10 on 2022-02-09 13:57

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lms.models.absences
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to=lms.models.absences.upload_to)),
            ],
            options={
                'verbose_name': 'Absence Attachment',
                'verbose_name_plural': 'Absence Attachments',
            },
        ),
        migrations.CreateModel(
            name='AbsenceTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_restriction_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Absence Time',
                'verbose_name_plural': 'Absence Time',
            },
        ),
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Achievement Type',
                'verbose_name_plural': 'Achievement Types',
            },
        ),
        migrations.CreateModel(
            name='Milfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True)),
                ('abbreviation', models.CharField(max_length=31)),
            ],
            options={
                'verbose_name': 'Military Faculty',
                'verbose_name_plural': 'Military Faculties',
            },
        ),
        migrations.CreateModel(
            name='Milgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, unique=True)),
                ('weekday', models.SmallIntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('milfaculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms.milfaculty')),
            ],
            options={
                'verbose_name': 'Military Group',
                'verbose_name_plural': 'Military Groups',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headdress', models.CharField(choices=[('CA', 'Кепка'), ('HA', 'Шапка')], max_length=2)),
                ('outerwear', models.CharField(choices=[('PC', 'Бушлат'), ('JA', 'Китель')], max_length=2)),
                ('gloves', models.BooleanField(default=False)),
                ('scarf', models.BooleanField(default=False)),
                ('milfaculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.milfaculty')),
            ],
            options={
                'verbose_name': 'Current uniform',
                'verbose_name_plural': 'Current uniforms',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(blank=True, max_length=64)),
                ('post', models.CharField(choices=[('CH', 'Начальник ВУЦ'), ('FH', 'Начальник цикла'), ('TE', 'Профессорско-преподавательский состав')], default='TE', max_length=2)),
                ('rank', models.CharField(choices=[('CA', 'Капитан'), ('MA', 'Майор'), ('LC', 'Подполковник'), ('CO', 'Полковник'), ('MG', 'Генерал-майор')], max_length=2)),
                ('birth_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.birthinfo')),
                ('contact_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.contactinfo')),
                ('milfaculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.milfaculty')),
                ('milgroups', models.ManyToManyField(blank=True, to='lms.Milgroup')),
                ('photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.photo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('EN', 'Зачислен'), ('ST', 'Обучается'), ('EX', 'Отчислен'), ('GR', 'Выпустился')], max_length=2)),
                ('post', models.CharField(blank=True, choices=[('GC', 'Командир взвода'), ('SC', 'Командир отделения')], default=None, max_length=2, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=64)),
                ('permanent_address', models.CharField(blank=True, max_length=128)),
                ('recruitment_office', models.CharField(blank=True, max_length=255)),
                ('birth_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.birthinfo')),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='common.contactinfo')),
                ('family', models.ManyToManyField(blank=True, null=True, to='common.Relative')),
                ('milgroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms.milgroup')),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.passport')),
                ('photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.photo')),
                ('skills', models.ManyToManyField(blank=True, to='lms.Skill')),
                ('university_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.universityinfo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PU', 'Взыскание'), ('RE', 'Выговор')], max_length=2)),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('remove_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.teacher')),
            ],
            options={
                'verbose_name': 'Punishment Journal',
                'verbose_name_plural': 'Punishment Journal',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LE', 'Лекция'), ('SE', 'Семинар'), ('GR', 'Групповое занятие'), ('PR', 'Практическое занятие'), ('FI', 'Зачет'), ('EX', 'Экзамен')], max_length=2)),
                ('date', models.DateField(default=datetime.date.today)),
                ('ordinal', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('milgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.milgroup')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.teacher')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Encouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EN', 'Благодарность'), ('RE', 'Снятие взыскания')], max_length=2)),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.teacher')),
            ],
            options={
                'verbose_name': 'Encouragement Journal',
                'verbose_name_plural': 'Encouragement Journal',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.achievementtype')),
            ],
            options={
                'verbose_name': 'Achievement Journal',
                'verbose_name_plural': 'Achievement Journal',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(2)]), size=None)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excuse', models.CharField(choices=[('LA', 'Опоздание'), ('LE', 'Уважительная'), ('IL', 'Неуважительная')], max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Открыт'), ('CL', 'Закрыт')], max_length=2)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(blank=True, max_length=127, null=True)),
                ('comment', models.CharField(blank=True, max_length=127, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.absenceattachment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
            options={
                'verbose_name': 'Absence Journal',
                'verbose_name_plural': 'Absence Journal',
                'unique_together': {('date', 'student')},
            },
        ),
    ]
