# Generated by Django 3.2.10 on 2022-09-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.birthinfo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='family',
            field=models.ManyToManyField(blank=True, null=True, to='common.Relative'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.passport'),
        ),
        migrations.AlterField(
            model_name='student',
            name='recruitment_office',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.universityinfo'),
        ),
    ]
