# Generated by Django 3.1.7 on 2021-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentoffice',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitmentoffice',
            name='city',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='recruitmentoffice',
            name='district',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
