# Generated by Django 3.1.7 on 2021-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('AP', 'абитуриент'), ('ST', 'обучающийся'), ('EX', 'отчислен'), ('GR', 'выпустился'), ('AW', 'в ожидании'), ('DE', 'отклонен')], default='AP', max_length=2),
        ),
    ]
