# Generated by Django 3.2.10 on 2022-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_make_student_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('LI', 'Лейтенант'), ('SL', 'Старший лейтенант'), ('CA', 'Капитан'), ('MA', 'Майор'), ('LC', 'Подполковник'), ('CO', 'Полковник'), ('MG', 'Генерал-майор')], max_length=2),
        ),
    ]
