# Generated by Django 3.2.10 on 2023-03-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_subject_milspecialty'),
        ('lms', '0003_add_lieutenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='milgroup',
            name='milspecialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.milspecialty'),
        ),
    ]
