# Generated by Django 3.1.7 on 2021-04-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_add_more_student_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('lesson', 'student')},
        ),
    ]
