# Generated by Django 3.1.7 on 2021-04-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_add_marks_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headdress', models.CharField(choices=[('CA', 'Кепка'), ('HA', 'Шапка')], max_length=2)),
                ('outerwear', models.CharField(choices=[('PC', 'Бушлат'), ('JA', 'Китель')], max_length=2)),
                ('milfaculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lms.milfaculty')),
            ],
            options={
                'verbose_name': 'Current uniform',
                'verbose_name_plural': 'Current uniforms',
            },
        ),
    ]
