# Generated by Django 3.2.3 on 2021-06-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_add_application_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Студент', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Student Post',
                'verbose_name_plural': 'Student Posts',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.studentpost'),
        ),
    ]
