# Generated by Django 3.2.3 on 2021-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_add_application_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='mean_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
