# Generated by Django 3.2.3 on 2021-06-08 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_add_student_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='mean_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
