# Generated by Django 3.2.20 on 2024-09-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_program_available_to_choose_for_applicants'),
        ('lms', '0007_alter_mark_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.contactinfo'),
        ),
    ]
