# Generated by Django 3.2.20 on 2023-11-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_renamed_password_to_passworddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='passport',
            new_name='personal_documents',
        ),
    ]
