# Generated by Django 3.2.3 on 2021-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_mean_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Student Skill',
                'verbose_name_plural': 'Student Skills',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_skills',
            field=models.ManyToManyField(blank=True, to='lms.StudentSkill'),
        ),
    ]
