# Generated by Django 3.2.20 on 2024-09-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_personal_documents_info'),
        ('lms', '0008_add_personal_documents_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.contactinfo'),
        ),
    ]
