# Generated by Django 3.2.20 on 2026-09-25 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0008_add_personal_documents_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('roster_count', models.PositiveIntegerField()),
                ('present_count', models.PositiveIntegerField()),
                ('excused_count', models.PositiveIntegerField()),
                ('unexcused_count', models.PositiveIntegerField()),
                ('unknown_count', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formation_reports', to=settings.AUTH_USER_MODEL)),
                ('milgroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms.milgroup')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_formation_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormationRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HC', 'Не стрижен'), ('UN', 'Нарушение формы одежды'), ('LA', 'Опоздал к построению'), ('OT', 'Другое')], max_length=2)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='lms.formationreport')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formationreport',
            constraint=models.CheckConstraint(check=models.Q(('roster_count', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('present_count'), '+', django.db.models.expressions.F('excused_count')), '+', django.db.models.expressions.F('unexcused_count')), '+', django.db.models.expressions.F('unknown_count')))), name='formation_counts_match_roster'),
        ),
        migrations.AlterUniqueTogether(
            name='formationreport',
            unique_together={('milgroup', 'date')},
        ),
    ]
