# Generated by Django 3.2.3 on 2021-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_add_student_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absencetime',
            options={'verbose_name': 'Absence Time', 'verbose_name_plural': 'Absence Time'},
        ),
    ]
