# Generated by Django 3.2.3 on 2021-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_fix_absence_time_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='milgroup',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
