name: "Back end"

on: [push]

jobs:
  main:
    name: "Build, tests, style, lint"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run:  cp .env.example .env
      - run:  cp back-end/.env.example back-end/.env
      - run:  cp tgbot/.env.example tgbot/.env
      - run:  cp watchdoc/.env.example watchdoc/.env
      - name: "Build back-end container"
        run:  docker compose build back-end
      - name: "Run Postgres in background"
        run:  docker compose up -d postgres
      - name: "Run tests"
        run:  docker compose run back-end scripts/test.sh
      - name: "Check code style"
        run:  docker compose run back-end scripts/format.sh --check
      # - name: "Lint code"
      #   run:  docker-compose run back-end scripts/lint.sh
      - name: "Stop all containers"
        run:  docker compose down
