name: "Front end"

on: [push]

jobs:
  main:
    name: "Build, style"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run:  cp .env.example .env
      - run:  cp back-end/.env.example back-end/.env
      - run:  cp tgbot/.env.example tgbot/.env
      - run:  cp watchdoc/.env.example watchdoc/.env
      - name: "Install NPM packages"
        run: cd front-end && npm install
      - name: "Check code style"
        run: cd front-end && npm run lint .
      - name: "Build front end container"
        run:  docker-compose build front-end
